
monitoring_directory: /opt/monitoring
monitoring_role:

# Grafana
monitoring_grafana_docker_image: grafana/grafana
monitoring_grafana_docker_image_version: latest
monitoring_grafana_host_port: 3001


# Prometheus
monitoring_prometheus_docker_image: docker.io/prom/prometheus
monitoring_prometheus_docker_image_version: latest
monitoring_prometheus_host_port: 9090
monitoring_prometheus_configuration_file_src_path:

# cAdvisor
monitoring_cadvisor_docker_image: gcr.io/cadvisor/cadvisor
monitoring_cadvisor_docker_image_version: v0.49.1
monitoring_cadvisor_host_port: 8098
