# Everything related to the arr stack
base_storage_mount_point: /opt/data

# gluetun variables
gluetun_docker_container_name: gluetun

gluetun_extra_ports:
  - "{{ qbittorrent_docker_port_ui }}:{{ qbittorrent_docker_port_ui }}"
  - "{{ qbittorrent_docker_port }}:{{ qbittorrent_docker_port }}"
  - "{{ qbittorrent_docker_port_udp }}:{{ qbittorrent_docker_port_udp }}/udp"
  - "{{ prowlarr_docker_port }}:{{ prowlarr_docker_port }}"
  - "{{ radarr_docker_port }}:{{ radarr_docker_port }}"
  - "{{ sonarr_docker_port }}:{{ sonarr_docker_port }}"

## VPN configuration
gluetun_vpn_service_provider: mullvad
gluetun_vpn_type: wireguard
gluetun_vpn_wireguard_addresses: 10.64.34.155/32
gluetun_vpn_wireguard_private_key:  !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35343837376561373261313561356431393462356530653134306232353936393032376234333530
    6637336565333030313163393665396431656433386632330a333663363132373764306436393237
    66363336316664666139353066323765323732626335343062303831356339326438303931306439
    3233623435393466390a326165316431623231326334666430373231353833303639356262663664
    39643632666235663363313866333238323561353830316663613632626538663831366330346338
    3331626661316165326664376137363066346262386461303335


# arr stack variables
arr_stack_use_vpn_routing: true
arr_stack_vpn_container_name: "{{ gluetun_docker_container_name }}"
arr_stack_host_shared_data_dir: "{{ base_storage_mount_point }}/media"
arr_stack_media_user_puid: 2000
arr_stack_media_user_pgid: 2000

## arr stack - radarr variable
arr_stack_radarr_enabled: true
radarr_docker_port: 7878

## arr stack - sonarr variable
arr_stack_sonarr_enabled: true
sonarr_docker_port: 8989

## arr stack - prowlarr variable
arr_stack_prowlarr_enabled: true
prowlarr_docker_port: 9696

## arr stack - qbittorrent variable
arr_stack_qbittorrent_enabled: true
qbittorrent_docker_port_ui: 8081
qbittorrent_docker_port: 6881
qbittorrent_docker_port_udp: 6881

## arr stack - jellyseerr variable
arr_stack_jellyseerr_enabled: true

## arr stack - jellyfin variable
arr_stack_jellyfin_enabled: true

# Monitoring stack variables
monitoring_role: "node"