all:
  children:
    bastion-servers:
      hosts:
        bastion-01:
          ansible_host: 192.168.1.160
          ansible_user: ansible
          ansible_become: true
    media-servers:
      hosts:
        media-01:
          ansible_host: 192.168.1.161
          ansible_user: ansible
          ansible_become: true
