all:
  children:
    bastion-servers:
      hosts:
        bastion-01:
          ansible_host: 192.168.1.151
          ansible_user: serveradmin
          ansible_become: true
    media-servers:
      hosts:
        media-01:
          ansible_host: 192.168.1.152
          ansible_user: serveradmin
          ansible_become: true
